export const familyMembers = [
  { id: 'mom', name: 'Мама', role: 'parent', color: '#0f766e', demoPin: '0000' },
  { id: 'veronika', name: 'Вероника', age: 14, role: 'child', color: '#c026d3', demoPin: '1414' },
  { id: 'diana', name: 'Диана', age: 12, role: 'child', color: '#2563eb', demoPin: '1212' },
];

export const tasks = [
  { id: 'kitchen-dishes', title: 'Кухня: посуда и раковина', area: '1 этаж - кухня', points: 2, cadence: 'ежедневно' },
  { id: 'kitchen-towels', title: 'Кухня: сменить полотенца', area: '1 этаж - кухня', points: 1, cadence: '2 раза в неделю' },
  { id: 'kitchen-trash-empty', title: 'Кухня: опорожнить мусорное ведро', area: '1 этаж - кухня', points: 1, cadence: 'ежедневно' },
  { id: 'kitchen-trash-wash', title: 'Кухня: вымыть мусорное ведро', area: '1 этаж - кухня', points: 2, cadence: '1 раз в неделю' },
  { id: 'all-devices-charge', title: 'Дом: зарядить все приборы - светильник у кофемашины, электронные ведра и дозаторы', area: 'общие задачи', points: 1, cadence: 'по выходным' },
  { id: 'kitchen-surfaces', title: 'Кухня: столешницы, стол, плита', area: '1 этаж - кухня', points: 2, cadence: 'ежедневно' },
  { id: 'soft-furniture-wash', title: 'Общее: помыть мягкую мебель на кухне, в гостиной и комнатах', area: 'общие задачи', points: 6, cadence: '1 раз в сезон' },
  { id: 'bedding-change', title: 'Общее: заменить постельное белье в комнатах', area: 'общие задачи', points: 4, cadence: '1 раз в неделю' },
  { id: 'air-conditioners-clean', title: 'Общее: почистить кондиционеры в гостиной и комнатах', area: 'общие задачи', points: 6, cadence: '1 раз в сезон' },
  { id: 'rags-mats-wash', title: 'Общее: постирать тряпки и коврики', area: 'общие задачи', points: 3, cadence: '1 раз в неделю' },
  { id: 'kitchen-fridge', title: 'Кухня: проверить холодильник и выбросить лишнее', area: '1 этаж - кухня', points: 2, cadence: '1 раз в неделю' },
  { id: 'kitchen-facades-backsplash', title: 'Кухня: фасады и фартук', area: '1 этаж - кухня', points: 3, cadence: '1 раз в неделю' },
  { id: 'kitchen-fridge-defrost', title: 'Кухня: разморозка и мытье холодильника', area: '1 этаж - кухня', points: 6, cadence: '1 раз в 2-3 месяца' },
  { id: 'kitchen-oven', title: 'Кухня: мытье духовки', area: '1 этаж - кухня', points: 5, cadence: '1 раз в месяц' },
  { id: 'kitchen-hob', title: 'Кухня: тщательно вымыть варочные панели', area: '1 этаж - кухня', points: 4, cadence: '1 раз в неделю' },
  { id: 'kitchen-hood', title: 'Кухня: почистить вытяжку', area: '1 этаж - кухня', points: 4, cadence: '1 раз в месяц' },
  { id: 'kitchen-lights', title: 'Кухня: протереть светильники', area: '1 этаж - кухня', points: 2, cadence: '1 раз в месяц' },
  { id: 'kitchen-window-door', title: 'Кухня: помыть окно и стеклянную дверь в сад', area: '1 этаж - кухня', points: 5, cadence: '1 раз в сезон' },
  { id: 'kitchen-curtains', title: 'Кухня: снять, постирать и повесить шторы', area: '1 этаж - кухня', points: 5, cadence: '2 раза в год' },
  { id: 'living-room-reset', title: 'Гостиная: убрать вещи по местам', area: '1 этаж - гостиная', points: 2, cadence: 'ежедневно' },
  { id: 'living-room-dust', title: 'Гостиная: протереть пыль', area: '1 этаж - гостиная', points: 2, cadence: '2 раза в неделю' },
  { id: 'living-room-sofa', title: 'Гостиная: привести в порядок диван и пледы', area: '1 этаж - гостиная', points: 1, cadence: 'ежедневно' },
  { id: 'living-room-window', title: 'Гостиная: помыть окно', area: '1 этаж - гостиная', points: 3, cadence: '1 раз в сезон' },
  { id: 'living-room-curtains', title: 'Гостиная: снять, постирать и повесить шторы', area: '1 этаж - гостиная', points: 5, cadence: '2 раза в год' },
  { id: 'living-room-lights', title: 'Гостиная: протереть светильники и люстры', area: '1 этаж - гостиная', points: 2, cadence: '1 раз в месяц' },
  { id: 'hallway-dust', title: 'Коридор 1 этажа: пыль, выключатели, ручки', area: '1 этаж - коридор', points: 2, cadence: '1 раз в неделю' },
  { id: 'hallway-lights', title: 'Коридор 1 этажа: протереть светильники', area: '1 этаж - коридор', points: 2, cadence: '1 раз в месяц' },
  { id: 'bathroom-1-sink', title: 'Ванная 1 этажа: раковина', area: '1 этаж - ванная', points: 2, cadence: '2 раза в неделю' },
  { id: 'bathroom-1-mirror', title: 'Ванная 1 этажа: протереть зеркало', area: '1 этаж - ванная', points: 1, cadence: '1 раз в неделю' },
  { id: 'bathroom-1-towels', title: 'Ванная 1 этажа: сменить полотенца, постирать и развесить', area: '1 этаж - ванная', points: 3, cadence: '2 раза в неделю' },
  { id: 'bathroom-1-paper-trash', title: 'Ванная 1 этажа: сжечь бумажные отходы из мусорного ведра', area: '1 этаж - ванная', points: 2, cadence: '2 раза в неделю' },
  { id: 'bathroom-1-toilet', title: 'Ванная 1 этажа: унитаз', area: '1 этаж - ванная', points: 3, cadence: '2 раза в неделю' },
  { id: 'bathroom-1-shower', title: 'Ванная 1 этажа: душевая кабина', area: '1 этаж - ванная', points: 3, cadence: '1 раз в неделю' },
  { id: 'bathroom-1-walls', title: 'Ванная 1 этажа: протереть стены из керамогранита', area: '1 этаж - ванная', points: 3, cadence: '1 раз в неделю' },
  { id: 'bathroom-1-laundry', title: 'Ванная 1 этажа: зона стиральной машины', area: '1 этаж - ванная', points: 2, cadence: '1 раз в неделю' },
  { id: 'bathroom-1-floor', title: 'Ванная 1 этажа: пол и коврик', area: '1 этаж - ванная', points: 2, cadence: '2 раза в неделю' },
  { id: 'bathroom-1-window', title: 'Ванная 1 этажа: помыть окно', area: '1 этаж - ванная', points: 3, cadence: '1 раз в сезон' },
  { id: 'bathroom-1-lights', title: 'Ванная 1 этажа: протереть светильники', area: '1 этаж - ванная', points: 2, cadence: '1 раз в месяц' },
  { id: 'entryway-shoes', title: 'Прихожая: обувь и верхняя одежда', area: '1 этаж - прихожая', points: 2, cadence: 'ежедневно' },
  { id: 'entryway-shoes-wash', title: 'Прихожая: вымыть обувь', area: '1 этаж - прихожая', points: 2, cadence: 'по необходимости' },
  { id: 'floor-washer-water', title: 'Кухня: робот-мойщик - опорожнить, сменить воду и промыть контейнер', area: '1 этаж - кухня', points: 2, cadence: '2 раза в неделю' },
  { id: 'floor-washer-clean', title: 'Кухня: робот-мойщик - почистить щетки, тряпку и фильтр', area: '1 этаж - кухня', points: 3, cadence: '2 раза в неделю' },
  { id: 'entryway-shelves', title: 'Прихожая: полки, сумки, мелочи', area: '1 этаж - прихожая', points: 2, cadence: '1 раз в неделю' },
  { id: 'entryway-mirror', title: 'Прихожая: протереть зеркало', area: '1 этаж - прихожая', points: 1, cadence: '1 раз в неделю' },
  { id: 'entryway-window', title: 'Прихожая: помыть окно', area: '1 этаж - прихожая', points: 3, cadence: '1 раз в сезон' },
  { id: 'entryway-lights', title: 'Прихожая: протереть светильники', area: '1 этаж - прихожая', points: 2, cadence: '1 раз в месяц' },
  { id: 'stairs-wash', title: 'Лестница: помыть ступени в 2 пролетах', area: 'лестница', points: 3, cadence: '1 раз в неделю' },
  { id: 'stairs-windowsill', title: 'Лестница: протереть пыль на подоконнике', area: 'лестница', points: 1, cadence: '1 раз в неделю' },
  { id: 'stairs-rail', title: 'Лестница: перила и пыль', area: 'лестница', points: 2, cadence: '1 раз в неделю' },
  { id: 'stairs-lights', title: 'Лестница: протереть светильники', area: 'лестница', points: 2, cadence: '1 раз в месяц' },
  { id: 'office-dust', title: 'Кабинет: пыль и проветривание', area: '1 этаж - кабинет', points: 2, cadence: '1 раз в месяц' },
  { id: 'office-floor', title: 'Кабинет: пол', area: '1 этаж - кабинет', points: 2, cadence: '1 раз в месяц' },
  { id: 'office-window', title: 'Кабинет: помыть окно', area: '1 этаж - кабинет', points: 3, cadence: '1 раз в сезон' },
  { id: 'office-lights', title: 'Кабинет: протереть светильники', area: '1 этаж - кабинет', points: 2, cadence: '1 раз в месяц' },
  { id: 'upstairs-hall', title: 'Коридор 2 этажа: порядок в проходе', area: '2 этаж - коридор', points: 1, cadence: 'через день' },
  { id: 'upstairs-hall-dust', title: 'Коридор 2 этажа: пыль и мелочи', area: '2 этаж - коридор', points: 2, cadence: '1 раз в неделю' },
  { id: 'upstairs-hall-lights', title: 'Коридор 2 этажа: протереть светильники', area: '2 этаж - коридор', points: 2, cadence: '1 раз в месяц' },
  { id: 'wardrobe', title: 'Гардеробная: разложить вещи', area: '2 этаж - гардеробная', points: 3, cadence: '1 раз в неделю' },
  { id: 'wardrobe-floor', title: 'Гардеробная: пол и пыль', area: '2 этаж - гардеробная', points: 2, cadence: '1 раз в неделю' },
  { id: 'wardrobe-mirror', title: 'Гардеробная: протереть зеркало', area: '2 этаж - гардеробная', points: 1, cadence: '1 раз в неделю' },
  { id: 'wardrobe-lights', title: 'Гардеробная: протереть светильники', area: '2 этаж - гардеробная', points: 2, cadence: '1 раз в месяц' },
  { id: 'wardrobe-season-change', title: 'Гардеробная: смена одежды и обуви по сезонам', area: '2 этаж - гардеробная', points: 6, cadence: '2 раза в год' },
  { id: 'mom-room-reset', title: 'Мамина комната: убрать вещи по местам', area: '2 этаж - мамина комната', points: 2, cadence: 'ежедневно' },
  { id: 'mom-room-dust', title: 'Мамина комната: пыль и поверхности', area: '2 этаж - мамина комната', points: 2, cadence: '1 раз в неделю' },
  { id: 'mom-room-mirror', title: 'Мамина комната: протереть зеркало', area: '2 этаж - мамина комната', points: 1, cadence: '1 раз в неделю' },
  { id: 'mom-room-window', title: 'Мамина комната: помыть окно', area: '2 этаж - мамина комната', points: 3, cadence: '1 раз в сезон' },
  { id: 'mom-room-curtains', title: 'Мамина комната: снять, постирать и повесить шторы', area: '2 этаж - мамина комната', points: 5, cadence: '2 раза в год' },
  { id: 'mom-room-lights', title: 'Мамина комната: протереть светильники и люстры', area: '2 этаж - мамина комната', points: 2, cadence: '1 раз в месяц' },
  { id: 'diana-room-reset', title: 'Дианина комната: личный порядок', area: '2 этаж - комната Дианы', points: 3, cadence: 'ежедневно' },
  { id: 'diana-room-desk', title: 'Дианина комната: стол и школьные вещи', area: '2 этаж - комната Дианы', points: 2, cadence: 'ежедневно' },
  { id: 'diana-room-dust', title: 'Дианина комната: пыль', area: '2 этаж - комната Дианы', points: 2, cadence: '1 раз в неделю' },
  { id: 'diana-room-clothes', title: 'Дианина комната: одежда и белье', area: '2 этаж - комната Дианы', points: 2, cadence: 'через день' },
  { id: 'diana-room-window', title: 'Дианина комната: помыть окно', area: '2 этаж - комната Дианы', points: 3, cadence: '1 раз в сезон' },
  { id: 'diana-room-lights', title: 'Дианина комната: протереть светильники и люстры', area: '2 этаж - комната Дианы', points: 2, cadence: '1 раз в месяц' },
  { id: 'veronika-room-reset', title: 'Вероникина комната: личный порядок', area: '2 этаж - комната Вероники', points: 3, cadence: 'ежедневно' },
  { id: 'veronika-room-desk', title: 'Вероникина комната: стол и учебные вещи', area: '2 этаж - комната Вероники', points: 2, cadence: 'ежедневно' },
  { id: 'veronika-room-dust', title: 'Вероникина комната: пыль', area: '2 этаж - комната Вероники', points: 2, cadence: '1 раз в неделю' },
  { id: 'veronika-room-clothes', title: 'Вероникина комната: одежда и белье', area: '2 этаж - комната Вероники', points: 2, cadence: 'через день' },
  { id: 'veronika-room-window', title: 'Вероникина комната: помыть окно', area: '2 этаж - комната Вероники', points: 3, cadence: '1 раз в сезон' },
  { id: 'veronika-room-lights', title: 'Вероникина комната: протереть светильники и люстры', area: '2 этаж - комната Вероники', points: 2, cadence: '1 раз в месяц' },
  { id: 'bathroom-2-laundry', title: 'Ванная 2 этажа: белье, сушилка, отпариватель', area: '2 этаж - ванная', points: 3, cadence: 'по необходимости' },
  { id: 'laundry-hang', title: 'Ванная 2 этажа: развесить белье после стирки', area: '2 этаж - ванная', points: 3, cadence: '1-2 раза в неделю' },
  { id: 'laundry-iron', title: 'Ванная 2 этажа: глажка после стирки', area: '2 этаж - ванная', points: 4, cadence: 'на следующий день после стирки', triggerAfterTaskId: 'laundry-hang', delayDays: 1 },
  { id: 'bathroom-2-sink', title: 'Ванная 2 этажа: раковина', area: '2 этаж - ванная', points: 2, cadence: '2 раза в неделю' },
  { id: 'bathroom-2-mirror', title: 'Ванная 2 этажа: протереть зеркало', area: '2 этаж - ванная', points: 1, cadence: '1 раз в неделю' },
  { id: 'bathroom-2-towels', title: 'Ванная 2 этажа: сменить полотенца, постирать и развесить', area: '2 этаж - ванная', points: 3, cadence: '2 раза в неделю' },
  { id: 'bathroom-2-paper-trash', title: 'Ванная 2 этажа: сжечь бумажные отходы из мусорного ведра', area: '2 этаж - ванная', points: 2, cadence: '2 раза в неделю' },
  { id: 'bathroom-2-toilet', title: 'Ванная 2 этажа: унитаз', area: '2 этаж - ванная', points: 3, cadence: '2 раза в неделю' },
  { id: 'bathroom-2-shower-bath', title: 'Ванная 2 этажа: душ и ванна', area: '2 этаж - ванная', points: 4, cadence: '1 раз в неделю' },
  { id: 'bathroom-2-walls', title: 'Ванная 2 этажа: протереть стены из керамогранита', area: '2 этаж - ванная', points: 3, cadence: '1 раз в неделю' },
  { id: 'bathroom-2-cabinet', title: 'Ванная 2 этажа: комод, шкаф, лишние вещи', area: '2 этаж - ванная', points: 2, cadence: '1 раз в неделю' },
  { id: 'bathroom-2-floor', title: 'Ванная 2 этажа: пол и коврики', area: '2 этаж - ванная', points: 2, cadence: '2 раза в неделю' },
  { id: 'bathroom-2-window', title: 'Ванная 2 этажа: помыть окно', area: '2 этаж - ванная', points: 3, cadence: '1 раз в сезон' },
  { id: 'bathroom-2-lights', title: 'Ванная 2 этажа: протереть светильники', area: '2 этаж - ванная', points: 2, cadence: '1 раз в месяц' },
  { id: 'upstairs-vacuum-clean', title: 'Робот-пылесос 2 этажа: вычистить контейнер, щетки и фильтр', area: '2 этаж - робот-пылесос', points: 3, cadence: '1 раз в неделю' },
  { id: 'garden-water', title: 'Полить грядки и цветники', area: 'огород', points: 1, cadence: 'ежедневно' },
  { id: 'garden-weed', title: 'Прополоть грядки или цветники', area: 'огород', points: 2, cadence: 'периодически' },
  { id: 'lawn-mow', title: 'Газон: покосить траву', area: 'огород', points: 5, cadence: 'по мере роста травы' },
  { id: 'lawn-weed', title: 'Газон: прополка сорняков', area: 'огород', points: 3, cadence: 'периодически' },
  { id: 'garden-old-leaves', title: 'Огород: вынести старую листву за пределы участка', area: 'огород', points: 4, cadence: 'по необходимости' },
  { id: 'front-lawn-mow', title: 'Перед участком: покосить траву', area: 'огород', points: 5, cadence: 'по мере роста травы' },
  { id: 'garden-harvest', title: 'Огород: собрать урожай или сухие цветы', area: 'огород', points: 2, cadence: 'по необходимости' },
  { id: 'garden-tools', title: 'Огород: убрать инвентарь и шланг', area: 'огород', points: 1, cadence: 'после работ' },
];

export const homeZones = [
  {
    id: 'shared',
    title: 'Общее',
    zones: [
      { id: 'shared-tasks', title: 'Общие задачи', match: 'общие задачи' },
    ],
  },
  {
    id: 'floor-1',
    title: '1 этаж',
    zones: [
      { id: 'kitchen', title: 'Кухня', match: 'кухня' },
      { id: 'living-room', title: 'Гостиная', match: 'гостиная' },
      { id: 'hallway-1', title: 'Коридор', match: 'коридор' },
      { id: 'bathroom-1', title: 'Ванная', match: '1 этаж - ванная' },
      { id: 'entryway', title: 'Прихожая', match: 'прихожая' },
      { id: 'office', title: 'Кабинет', match: 'кабинет' },
      { id: 'stairs', title: 'Лестница', match: 'лестница' },
    ],
  },
  {
    id: 'floor-2',
    title: '2 этаж',
    zones: [
      { id: 'hallway-2', title: 'Коридор', match: '2 этаж - коридор' },
      { id: 'wardrobe', title: 'Гардеробная', match: 'гардеробная' },
      { id: 'mom-room', title: 'Мамина комната', match: 'мамина комната' },
      { id: 'diana-room', title: 'Комната Дианы', match: 'комната Дианы' },
      { id: 'veronika-room', title: 'Комната Вероники', match: 'комната Вероники' },
      { id: 'bathroom-2', title: 'Ванная', match: '2 этаж - ванная' },
      { id: 'upstairs-vacuum', title: 'Робот-пылесос', match: 'робот-пылесос' },
    ],
  },
  {
    id: 'garden',
    title: 'Огород',
    zones: [
      { id: 'garden-beds', title: 'Грядки и цветники', match: 'огород' },
    ],
  },
];

export const personalRewards = [
  { id: 'sweet', title: 'Вкусный напиток или сладость', points: 10 },
  { id: 'free-evening', title: 'Вечер без обязанностей', points: 20 },
  { id: 'cinema-cafe', title: 'Кино или кафе', points: 30 },
  { id: 'small-buy', title: 'Покупка в пределах 300 рублей', points: 50 },
  { id: 'special-day', title: 'Особенный день для ребенка или мамы', points: 70 },
];

export const teamRewards = [
  { id: 'family-dessert', title: 'Вкусный ужин или десерт вместе', points: 100 },
  { id: 'family-evening', title: 'Семейный вечер: фильм, игра или пикник', points: 150 },
  { id: 'family-trip', title: 'Поездка или развлечение по выбору', points: 200 },
  { id: 'dream-day', title: 'Большой семейный день мечты', points: 250 },
];

export const initialState = {
  schemaVersion: 5,
  activeMemberId: null,
  avatars: {},
  avatarUpdatedAt: {},
  completed: [],
  purchases: [],
  customTasks: [],
  passwordResetRequests: [],
  taskAssignments: [],
  taskReviews: [],
  notifications: [],
  syncTombstones: {
    completed: {},
    purchases: {},
    customTasks: {},
    passwordResetRequests: {},
    taskAssignments: {},
    taskReviews: {},
    notifications: {},
  },
};
